# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarnedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('warning_count', models.IntegerField(default=1)),
            ],
        ),
    ]
